apiVersion: v1
kind: Service
metadata:
  name: primary
spec:
  type: NodePort
  selector:
    name: redis-primary
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: redis-primary
    nodePort: 32002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primary-deployment
  labels:
    name: redis-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-primary
  template:
    metadata:
      labels:
        name: redis-primary
    spec:
      subdomain: primary
      containers:
      - name: redis
        image: redis:3.2.0-alpine
        command:
          - "redis-server"
        args:
          - "--protected-mode"
          - "no"
        ports:
        - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodepod
  labels:
    app: the-node-pod
spec:
  selector:
    matchLabels:
      app: the-node-pod
  template:
    metadata:
      labels:
        app: the-node-pod
    spec:
      containers:
      - name: server
        image: nodeserver:latest
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  type: NodePort
  selector:
    app: the-node-pod
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 32000

