apiVersion: v1
kind: Pod
metadata:
  name: javapod
  labels:
    app: the-java-pod
spec:
  containers:
  - name: server
    image: javaserver
    imagePullPolicy: Never
    volumeMounts:
    - name: secrets
      mountPath: /secrets
    envFrom:
    - configMapRef:
        name: server-env
    resources:
      limits:
        cpu: 1
        memory: 128Mi
      requests:
        cpu: "500m"
        memory: 64Mi
  volumes:
  - name: secrets
    secret:
      secretName: server-secret
---
apiVersion: v1
kind: Service
metadata:
  name: the-server-service
spec:
  type: NodePort
  selector:
    app: the-java-pod
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-env
data:
  SERVERNAME: Frank
---
apiVersion: v1
kind: Secret
metadata:
  name: server-secret
data:
  password: cGFzc3dvcmQ=
