apiVersion: v1
kind: Pod
metadata:
  name: gopod
  labels:
    app: the-go-pod
spec:
  containers:
  - name: server
    image: goserver
    imagePullPolicy: Never
    resources:
      limits:
        cpu: 1
        memory: 128Mi
      requests:
        cpu: "500m"
        memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: the-server-service
spec:
  type: NodePort
  selector:
    app: the-go-pod
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30080
